---
# tasks file for slave_node

- name: Installing docker
  package:
    name: docker
    state: present

- name: Enableling Docker Services
  service:
    name: docker
    state: started
    enabled: yes

- name: Configuring YUM Repo For K8S Services
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: 1
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  changed_when: false


- name: Installing k8s softwares for Slave
  package:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - iproute-tc
    - kubectl
  changed_when: false

- name: Enableling Kubelet Services
  service:
    name: kubelet
    state: started
    enabled: yes
  changed_when: false

- name: Changing CGROUP Driver of Docker To systemd
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
  changed_when: false

- name: Restarting Docker Services
  service:
    name: docker
    state: restarted
  changed_when: false

- name: Setting Up IP Tables
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  changed_when: false

- name: Restarting sysctl
  shell: "sudo sysctl --system"
  changed_when: false

- name: Running Token File
  shell: "{{ tokens }}"

